#pragma once

#include "order.hpp"

#include <map>
#include <deque>
#include <unordered_map>
#include <vector>
#include <optional>
#include <functional>

// ---------------------------------------------------------------------------
// C++ concepts used in this file (this is your cheat sheet — look each of
// these up if it's unfamiliar, that's the entire "relearn C++" task):
//
//   std::map<K, V>        - a sorted associative container (red-black tree).
//                            Iterating it gives you keys in sorted order,
//                            which is exactly what a price-ordered book needs.
//   std::deque<T>         - a double-ended queue. We use it as a FIFO queue
//                            of orders sitting at the same price level, which
//                            gives us time priority "for free" (push_back to
//                            add, front()/pop_front() to match the oldest).
//   std::unordered_map    - a hash map, O(1) average lookup. Used so
//                            cancel(orderId) doesn't require scanning the
//                            whole book.
//   std::optional<T>      - a value that might not be present, instead of
//                            using a null pointer or a magic sentinel value.
//   std::vector<T>        - a dynamic array. Used for returning a list of
//                            trades generated by one call.
//
// None of these require manual new/delete — the containers own their memory.
// ---------------------------------------------------------------------------

class OrderBook {
public:
    // Submit a new order (limit or market). Matches it against the book
    // immediately; if it's a limit order with quantity left over, it rests
    // in the book. Returns every trade generated by this call (may be empty).
    std::vector<Trade> addOrder(Order order);

    // Cancel a resting order by id. Returns true if it was found and removed.
    bool cancelOrder(uint64_t orderId);

    // Inspection helpers, mainly for tests and the demo/CLI.
    std::optional<int64_t> bestBid() const;
    std::optional<int64_t> bestAsk() const;
    size_t bidLevels() const { return bids_.size(); }
    size_t askLevels() const { return asks_.size(); }
    size_t restingOrderCount() const { return locations_.size(); }

private:
    // Bids sorted highest price first (best bid = what a seller wants to see).
    std::map<int64_t, std::deque<Order>, std::greater<int64_t>> bids_;
    // Asks sorted lowest price first (best ask = what a buyer wants to see).
    std::map<int64_t, std::deque<Order>> asks_;

    // Where to find a resting order, so cancel() doesn't need to search
    // every price level.
    struct Location {
        Side side;
        int64_t price;
    };
    std::unordered_map<uint64_t, Location> locations_;

    uint64_t nextTimestamp_ = 0;

    std::vector<Trade> match(Order& incoming);
    void insertResting(Order order);
};
